### ISSUE TITLE
Using a remote schema

### ISSUE THREAD

**Issue by WaldoJeffers** [apollographql/eslint-plugin-graphql#114]
Hello,

This is a great project, very useful to avoid silly mistakes which are hard to catch before running in prod. I tried using this plugin with a `.graphqlconfig` file specifying different endpoints for remote schemas (is it actually possible?), something like:
```js
{
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "dev": "https://example.com/graphql"
    }
  }
}
```
But I'm sure as how to make it work with this plugin:
1. Is it possible to use a remote schema?
2. How can I tell `eslint-plugin-graphql` to use the remote schema? If I remove the `schemaPath`, the plugin throws an error.

Thanks!

**Comment by jnwng** [comment]
@WaldoJeffers while `.graphqlconfig` provides the _configuration_ for where the schema is located, it does not actually retrieve the schema for you (you can use the [graphql-cli](https://www.npmjs.com/package/graphql-cli)'s `graphql get-schema` to do that).

unfortunately due to the fact that [we can't have asynchronous code in ESLint rules](https://stackoverflow.com/a/33901740), it wouldn't be straightforward to block resolution to retrieve the schema. 

all the code here makes the assumption that the schema is available locally. i'd be happy to have a discussion about making the workflow a little more straightforward, but we don't currently have the ability to resolve against remote schemas.

**Comment by WaldoJeffers** [comment]
@jnwng Thanks for your answer 😄
