### ISSUE TITLE
Update graphql peer dependency

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/eslint-plugin-graphql#90]
`graphql@^0.11.0` needs to be supported.

I suspect this is causing this error when attempting to lint:

```
Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
```

**Comment by jnwng** [comment]
@jaydenseric turns out its slightly more complex, `graphql-config` _also_ has a dependency on `graphql` which we needed to take as well. see #91 which should update a few dependencies and be compatible with `graphql@^0.11.0`. do you mind trying `eslint-plugin-graphql@1.4.0-1` and let me know if that resolves the error you're seeing?

separately, we probably ought to see if `graphql-config` should be using `peerDependencies` as well.

**Comment by jaydenseric** [comment]
Just tried out `eslint-plugin-graphql@1.4.0-1`, and it fixed the error 🎉

**Comment by jnwng** [comment]
Boom! Alright, if you wouldn't mind poking at #91 just to make sure nothing
fishy is going on, I can get a release of 1.4.0 in an hour or so.
